export const filterOptions = [
  {
    id: 1,
    title: "propertyTypes",
    filterName: "Type of property",
    filterItems: ["House", "Apartment"],
    isOpen: true,
  },
  {
    id: 2,
    title: "size",
    filterName: "No. of Bedrooms",
    filterItems: ["1 BHK", "2 BHK", "3 BHK", "4 BHK"],
    isOpen: true,
  },
  {
    id: 3,
    title: "tenantTypes",
    filterName: "Tenant Type",
    filterItems: ["Family", "Bachelor"],
    isOpen: true,
  },
  {
    id: 4,
    title: "amenities",
    filterName: "Amenities",
    filterItems: [
      "Security / Fire Alarm",
      "Battery Backup",
      "Elevator",
      "Gym",
      "Parking",
      "Power Backup",
      "Swimming Pool",
      "Laundry Facilities",
      "Security Surveillance",
      "Maintenance Staff",
      "Waste Disposal",
    ],
    isOpen: true,
  },
  {
    id: 5,
    title: "furnishedStatuses",
    filterName: "Furnishing Status",
    filterItems: ["Unfurnished", "Semi Furnished", "Fully Furnished"],
    isOpen: true,
  },
];
